services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_output:/root/.n8n-files
      - ./snake_vid_flow.json:/home/node/snake_vid_flow.json
      - ./audio:/home/node/audio
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_FOLDER=/home/node/
      - NODES_EXCLUDE=[]
    entrypoint: >
      sh -c "
      pip install --break-system-packages --no-deps git+https://github.com/JesperFritsch/snake_sim.git --force-reinstall --quiet &&
      n8n import:workflow --input=/home/node/snake_vid_flow.json || true &&
      n8n
      "

volumes:
  n8n_data: